export const STORE_CREATE_REQUEST = 'STORE_CREATE_REQUEST'
export const STORE_CREATE_SUCCESS = 'STORE_CREATE_SUCCESS'
export const STORE_CREATE_FAIL = 'STORE_CREATE_FAIL'
export const STORE_CREATE_RESET = 'STORE_CREATE_RESET'

export const STORE_DETAILS_REQUEST = 'STORE_DETAILS_REQUEST'
export const STORE_DETAILS_SUCCESS = 'STORE_DETAILS_SUCCESS'
export const STORE_DETAILS_FAIL = 'STORE_DETAILS_FAIL'

export const STORE_DASHBOARD_REQUEST = 'STORE_DASHBOARD_REQUEST'
export const STORE_DASHBOARD_SUCCESS = 'STORE_DASHBOARD_SUCCESS'
export const STORE_DASHBOARD_FAIL = 'STORE_DASHBOARD_FAIL'


